### ISSUE TITLE
Inconsistency in AVLTree methods

### ISSUE THREAD

**Issue by johnoro** [LambdaSchool/Data-Structures#343]
`_left_rotate` and `_right_rotate` in AVLTree, https://github.com/LambdaSchool/Data-Structures/tree/master/avl_tree, are called incorrectly in the tests as `left_rotate` and `right_rotate` respectively. They should be called with underscores on the front, or they should not have underscores, so that the tests won't fail due to incorrect method names.

**Comment by seanchen1991** [comment]
Fixed. I removed the underscores from the method names in the skeleton code.
